[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# same carots in solidity... allow you to round up to the next version of the crate
rand = "0.8.4"
